sudo: require
services:
  - docker

before_install:
  - docker build -t yeungwingyuen/react-project/my-app -f Dockerfile.dev .

script:
  - docker run -e CI=true yeungwingyuen/react-project/my-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2"
  bucket_path: "docker-react"
  on:
    branch master
  access_key_id: $AWS_Access_key
  secret_access_key: "$AWS_Secret_key"